// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HackerNews.proto

package hnproto;

public final class PBMessages {
  private PBMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hnproto.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional bool deleted = 2;</code>
     */
    boolean hasDeleted();
    /**
     * <code>optional bool deleted = 2;</code>
     */
    boolean getDeleted();

    /**
     * <code>optional string _type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional string _type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string _type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string by = 4;</code>
     */
    boolean hasBy();
    /**
     * <code>optional string by = 4;</code>
     */
    java.lang.String getBy();
    /**
     * <code>optional string by = 4;</code>
     */
    com.google.protobuf.ByteString
        getByBytes();

    /**
     * <code>optional uint32 time = 5;</code>
     */
    boolean hasTime();
    /**
     * <code>optional uint32 time = 5;</code>
     */
    int getTime();

    /**
     * <code>optional string text = 6;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 6;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 6;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional bool dead = 7;</code>
     */
    boolean hasDead();
    /**
     * <code>optional bool dead = 7;</code>
     */
    boolean getDead();

    /**
     * <code>optional uint32 parent = 8;</code>
     */
    boolean hasParent();
    /**
     * <code>optional uint32 parent = 8;</code>
     */
    int getParent();

    /**
     * <code>repeated uint32 kids = 9;</code>
     */
    java.util.List<java.lang.Integer> getKidsList();
    /**
     * <code>repeated uint32 kids = 9;</code>
     */
    int getKidsCount();
    /**
     * <code>repeated uint32 kids = 9;</code>
     */
    int getKids(int index);

    /**
     * <code>optional string url = 10;</code>
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 10;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 10;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional uint32 score = 11;</code>
     */
    boolean hasScore();
    /**
     * <code>optional uint32 score = 11;</code>
     */
    int getScore();

    /**
     * <code>optional string title = 12;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 12;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 12;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated uint32 parts = 13;</code>
     */
    java.util.List<java.lang.Integer> getPartsList();
    /**
     * <code>repeated uint32 parts = 13;</code>
     */
    int getPartsCount();
    /**
     * <code>repeated uint32 parts = 13;</code>
     */
    int getParts(int index);

    /**
     * <code>optional uint32 descendents = 14;</code>
     */
    boolean hasDescendents();
    /**
     * <code>optional uint32 descendents = 14;</code>
     */
    int getDescendents();
  }
  /**
   * Protobuf type {@code hnproto.Item}
   */
  public static final class Item extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hnproto.Item)
      ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Item defaultInstance;
    public static Item getDefaultInstance() {
      return defaultInstance;
    }

    public Item getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              deleted_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              Type_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              by_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              time_ = input.readUInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              text_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              dead_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              parent_ = input.readUInt32();
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                kids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000100;
              }
              kids_.add(input.readUInt32());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
                kids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000100;
              }
              while (input.getBytesUntilLimit() > 0) {
                kids_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              url_ = bs;
              break;
            }
            case 88: {
              bitField0_ |= 0x00000200;
              score_ = input.readUInt32();
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              title_ = bs;
              break;
            }
            case 104: {
              if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
                parts_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00001000;
              }
              parts_.add(input.readUInt32());
              break;
            }
            case 106: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00001000) == 0x00001000) && input.getBytesUntilLimit() > 0) {
                parts_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00001000;
              }
              while (input.getBytesUntilLimit() > 0) {
                parts_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 112: {
              bitField0_ |= 0x00000800;
              descendents_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          kids_ = java.util.Collections.unmodifiableList(kids_);
        }
        if (((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
          parts_ = java.util.Collections.unmodifiableList(parts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hnproto.PBMessages.internal_static_hnproto_Item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hnproto.PBMessages.internal_static_hnproto_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hnproto.PBMessages.Item.class, hnproto.PBMessages.Item.Builder.class);
    }

    public static com.google.protobuf.Parser<Item> PARSER =
        new com.google.protobuf.AbstractParser<Item>() {
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DELETED_FIELD_NUMBER = 2;
    private boolean deleted_;
    /**
     * <code>optional bool deleted = 2;</code>
     */
    public boolean hasDeleted() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool deleted = 2;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }

    public static final int _TYPE_FIELD_NUMBER = 3;
    private java.lang.Object Type_;
    /**
     * <code>optional string _type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string _type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = Type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          Type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string _type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = Type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BY_FIELD_NUMBER = 4;
    private java.lang.Object by_;
    /**
     * <code>optional string by = 4;</code>
     */
    public boolean hasBy() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string by = 4;</code>
     */
    public java.lang.String getBy() {
      java.lang.Object ref = by_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          by_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string by = 4;</code>
     */
    public com.google.protobuf.ByteString
        getByBytes() {
      java.lang.Object ref = by_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        by_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private int time_;
    /**
     * <code>optional uint32 time = 5;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 time = 5;</code>
     */
    public int getTime() {
      return time_;
    }

    public static final int TEXT_FIELD_NUMBER = 6;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 6;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string text = 6;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEAD_FIELD_NUMBER = 7;
    private boolean dead_;
    /**
     * <code>optional bool dead = 7;</code>
     */
    public boolean hasDead() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool dead = 7;</code>
     */
    public boolean getDead() {
      return dead_;
    }

    public static final int PARENT_FIELD_NUMBER = 8;
    private int parent_;
    /**
     * <code>optional uint32 parent = 8;</code>
     */
    public boolean hasParent() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 parent = 8;</code>
     */
    public int getParent() {
      return parent_;
    }

    public static final int KIDS_FIELD_NUMBER = 9;
    private java.util.List<java.lang.Integer> kids_;
    /**
     * <code>repeated uint32 kids = 9;</code>
     */
    public java.util.List<java.lang.Integer>
        getKidsList() {
      return kids_;
    }
    /**
     * <code>repeated uint32 kids = 9;</code>
     */
    public int getKidsCount() {
      return kids_.size();
    }
    /**
     * <code>repeated uint32 kids = 9;</code>
     */
    public int getKids(int index) {
      return kids_.get(index);
    }

    public static final int URL_FIELD_NUMBER = 10;
    private java.lang.Object url_;
    /**
     * <code>optional string url = 10;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string url = 10;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 11;
    private int score_;
    /**
     * <code>optional uint32 score = 11;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 score = 11;</code>
     */
    public int getScore() {
      return score_;
    }

    public static final int TITLE_FIELD_NUMBER = 12;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 12;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string title = 12;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARTS_FIELD_NUMBER = 13;
    private java.util.List<java.lang.Integer> parts_;
    /**
     * <code>repeated uint32 parts = 13;</code>
     */
    public java.util.List<java.lang.Integer>
        getPartsList() {
      return parts_;
    }
    /**
     * <code>repeated uint32 parts = 13;</code>
     */
    public int getPartsCount() {
      return parts_.size();
    }
    /**
     * <code>repeated uint32 parts = 13;</code>
     */
    public int getParts(int index) {
      return parts_.get(index);
    }

    public static final int DESCENDENTS_FIELD_NUMBER = 14;
    private int descendents_;
    /**
     * <code>optional uint32 descendents = 14;</code>
     */
    public boolean hasDescendents() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint32 descendents = 14;</code>
     */
    public int getDescendents() {
      return descendents_;
    }

    private void initFields() {
      id_ = 0;
      deleted_ = false;
      Type_ = "";
      by_ = "";
      time_ = 0;
      text_ = "";
      dead_ = false;
      parent_ = 0;
      kids_ = java.util.Collections.emptyList();
      url_ = "";
      score_ = 0;
      title_ = "";
      parts_ = java.util.Collections.emptyList();
      descendents_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, deleted_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getByBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, time_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTextBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, dead_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, parent_);
      }
      for (int i = 0; i < kids_.size(); i++) {
        output.writeUInt32(9, kids_.get(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(11, score_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, getTitleBytes());
      }
      for (int i = 0; i < parts_.size(); i++) {
        output.writeUInt32(13, parts_.get(i));
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt32(14, descendents_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, deleted_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getByBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, time_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTextBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, dead_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, parent_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < kids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(kids_.get(i));
        }
        size += dataSize;
        size += 1 * getKidsList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, score_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getTitleBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parts_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(parts_.get(i));
        }
        size += dataSize;
        size += 1 * getPartsList().size();
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, descendents_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hnproto.PBMessages.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hnproto.PBMessages.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hnproto.PBMessages.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hnproto.PBMessages.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hnproto.PBMessages.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hnproto.PBMessages.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hnproto.PBMessages.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hnproto.PBMessages.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hnproto.PBMessages.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hnproto.PBMessages.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hnproto.PBMessages.Item prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hnproto.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hnproto.Item)
        hnproto.PBMessages.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hnproto.PBMessages.internal_static_hnproto_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hnproto.PBMessages.internal_static_hnproto_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hnproto.PBMessages.Item.class, hnproto.PBMessages.Item.Builder.class);
      }

      // Construct using hnproto.PBMessages.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        Type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        by_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        dead_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        parent_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        kids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        parts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
        descendents_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hnproto.PBMessages.internal_static_hnproto_Item_descriptor;
      }

      public hnproto.PBMessages.Item getDefaultInstanceForType() {
        return hnproto.PBMessages.Item.getDefaultInstance();
      }

      public hnproto.PBMessages.Item build() {
        hnproto.PBMessages.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hnproto.PBMessages.Item buildPartial() {
        hnproto.PBMessages.Item result = new hnproto.PBMessages.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deleted_ = deleted_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.Type_ = Type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.by_ = by_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.dead_ = dead_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.parent_ = parent_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          kids_ = java.util.Collections.unmodifiableList(kids_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.kids_ = kids_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.title_ = title_;
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          parts_ = java.util.Collections.unmodifiableList(parts_);
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.parts_ = parts_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.descendents_ = descendents_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hnproto.PBMessages.Item) {
          return mergeFrom((hnproto.PBMessages.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hnproto.PBMessages.Item other) {
        if (other == hnproto.PBMessages.Item.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDeleted()) {
          setDeleted(other.getDeleted());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          Type_ = other.Type_;
          onChanged();
        }
        if (other.hasBy()) {
          bitField0_ |= 0x00000008;
          by_ = other.by_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000020;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasDead()) {
          setDead(other.getDead());
        }
        if (other.hasParent()) {
          setParent(other.getParent());
        }
        if (!other.kids_.isEmpty()) {
          if (kids_.isEmpty()) {
            kids_ = other.kids_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureKidsIsMutable();
            kids_.addAll(other.kids_);
          }
          onChanged();
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000200;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000800;
          title_ = other.title_;
          onChanged();
        }
        if (!other.parts_.isEmpty()) {
          if (parts_.isEmpty()) {
            parts_ = other.parts_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensurePartsIsMutable();
            parts_.addAll(other.parts_);
          }
          onChanged();
        }
        if (other.hasDescendents()) {
          setDescendents(other.getDescendents());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hnproto.PBMessages.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hnproto.PBMessages.Item) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean deleted_ ;
      /**
       * <code>optional bool deleted = 2;</code>
       */
      public boolean hasDeleted() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool deleted = 2;</code>
       */
      public boolean getDeleted() {
        return deleted_;
      }
      /**
       * <code>optional bool deleted = 2;</code>
       */
      public Builder setDeleted(boolean value) {
        bitField0_ |= 0x00000002;
        deleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool deleted = 2;</code>
       */
      public Builder clearDeleted() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deleted_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object Type_ = "";
      /**
       * <code>optional string _type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string _type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = Type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            Type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string _type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = Type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string _type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        Type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string _type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        Type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string _type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        Type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object by_ = "";
      /**
       * <code>optional string by = 4;</code>
       */
      public boolean hasBy() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string by = 4;</code>
       */
      public java.lang.String getBy() {
        java.lang.Object ref = by_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            by_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string by = 4;</code>
       */
      public com.google.protobuf.ByteString
          getByBytes() {
        java.lang.Object ref = by_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          by_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string by = 4;</code>
       */
      public Builder setBy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        by_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string by = 4;</code>
       */
      public Builder clearBy() {
        bitField0_ = (bitField0_ & ~0x00000008);
        by_ = getDefaultInstance().getBy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string by = 4;</code>
       */
      public Builder setByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        by_ = value;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>optional uint32 time = 5;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 time = 5;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional uint32 time = 5;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000010;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 time = 5;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 6;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000020);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }

      private boolean dead_ ;
      /**
       * <code>optional bool dead = 7;</code>
       */
      public boolean hasDead() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool dead = 7;</code>
       */
      public boolean getDead() {
        return dead_;
      }
      /**
       * <code>optional bool dead = 7;</code>
       */
      public Builder setDead(boolean value) {
        bitField0_ |= 0x00000040;
        dead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool dead = 7;</code>
       */
      public Builder clearDead() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dead_ = false;
        onChanged();
        return this;
      }

      private int parent_ ;
      /**
       * <code>optional uint32 parent = 8;</code>
       */
      public boolean hasParent() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 parent = 8;</code>
       */
      public int getParent() {
        return parent_;
      }
      /**
       * <code>optional uint32 parent = 8;</code>
       */
      public Builder setParent(int value) {
        bitField0_ |= 0x00000080;
        parent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 parent = 8;</code>
       */
      public Builder clearParent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        parent_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> kids_ = java.util.Collections.emptyList();
      private void ensureKidsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          kids_ = new java.util.ArrayList<java.lang.Integer>(kids_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public java.util.List<java.lang.Integer>
          getKidsList() {
        return java.util.Collections.unmodifiableList(kids_);
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public int getKidsCount() {
        return kids_.size();
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public int getKids(int index) {
        return kids_.get(index);
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public Builder setKids(
          int index, int value) {
        ensureKidsIsMutable();
        kids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public Builder addKids(int value) {
        ensureKidsIsMutable();
        kids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public Builder addAllKids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureKidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, kids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 kids = 9;</code>
       */
      public Builder clearKids() {
        kids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 10;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string url = 10;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 10;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 10;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000200);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 10;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <code>optional uint32 score = 11;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint32 score = 11;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional uint32 score = 11;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000400;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 score = 11;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000400);
        score_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 12;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string title = 12;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 12;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 12;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000800);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 12;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        title_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> parts_ = java.util.Collections.emptyList();
      private void ensurePartsIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          parts_ = new java.util.ArrayList<java.lang.Integer>(parts_);
          bitField0_ |= 0x00001000;
         }
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public java.util.List<java.lang.Integer>
          getPartsList() {
        return java.util.Collections.unmodifiableList(parts_);
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public int getPartsCount() {
        return parts_.size();
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public int getParts(int index) {
        return parts_.get(index);
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public Builder setParts(
          int index, int value) {
        ensurePartsIsMutable();
        parts_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public Builder addParts(int value) {
        ensurePartsIsMutable();
        parts_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public Builder addAllParts(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePartsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parts_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 parts = 13;</code>
       */
      public Builder clearParts() {
        parts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
        return this;
      }

      private int descendents_ ;
      /**
       * <code>optional uint32 descendents = 14;</code>
       */
      public boolean hasDescendents() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional uint32 descendents = 14;</code>
       */
      public int getDescendents() {
        return descendents_;
      }
      /**
       * <code>optional uint32 descendents = 14;</code>
       */
      public Builder setDescendents(int value) {
        bitField0_ |= 0x00002000;
        descendents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 descendents = 14;</code>
       */
      public Builder clearDescendents() {
        bitField0_ = (bitField0_ & ~0x00002000);
        descendents_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hnproto.Item)
    }

    static {
      defaultInstance = new Item(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hnproto.Item)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hnproto_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hnproto_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HackerNews.proto\022\007hnproto\"\325\001\n\004Item\022\n\n\002" +
      "id\030\001 \001(\r\022\017\n\007deleted\030\002 \001(\010\022\r\n\005_type\030\003 \001(\t" +
      "\022\n\n\002by\030\004 \001(\t\022\014\n\004time\030\005 \001(\r\022\014\n\004text\030\006 \001(\t" +
      "\022\014\n\004dead\030\007 \001(\010\022\016\n\006parent\030\010 \001(\r\022\014\n\004kids\030\t" +
      " \003(\r\022\013\n\003url\030\n \001(\t\022\r\n\005score\030\013 \001(\r\022\r\n\005titl" +
      "e\030\014 \001(\t\022\r\n\005parts\030\r \003(\r\022\023\n\013descendents\030\016 " +
      "\001(\rB\025\n\007hnprotoB\nPBMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hnproto_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hnproto_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hnproto_Item_descriptor,
        new java.lang.String[] { "Id", "Deleted", "Type", "By", "Time", "Text", "Dead", "Parent", "Kids", "Url", "Score", "Title", "Parts", "Descendents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
